CREATE DATABASE quanglybanhang;
USE quanlybanhang;

CREATE TABLE Customer(
cID INT PRIMARY KEY NOT NULL,
cName VARCHAR(30),
cAge INT
);

CREATE TABLE `Order`(
oID INT PRIMARY KEY NOT NULL,
cID INT NOT NULL,
oDate DATETIME,
oTotalPrice DECIMAL,
FOREIGN KEY(cID) REFERENCES Customer (cID)
);

CREATE TABLE Product(
pID INT PRIMARY KEY NOT NULL,
pName VARCHAR(30),
pPrice DECIMAL
);

CREATE TABLE OrderDetail(
oID INT,
pID INT,
odQTY DOUBLE,
PRIMARY KEY (oID, pID),
FOREIGN KEY(oID) REFERENCES `Order` (oID),
FOREIGN KEY(pID) REFERENCES Product (pID)
);

